// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiVIFv2jZyPPS14We4DWbwvmpRoNm2Uk',
    appId: '1:829011178828:web:85d36fc082bca2e6790be9',
    messagingSenderId: '829011178828',
    projectId: 'flutter-drivenui',
    authDomain: 'flutter-drivenui.firebaseapp.com',
    storageBucket: 'flutter-drivenui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPtiemK_PpJz9LKpNPiUYA9Crf1WcE7g',
    appId: '1:829011178828:android:f864cf8f4f55cb72790be9',
    messagingSenderId: '829011178828',
    projectId: 'flutter-drivenui',
    storageBucket: 'flutter-drivenui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4eD4iL0VTRWHMVXRZelP_8JyBFxC8mHg',
    appId: '1:829011178828:ios:d5a9707775dcdaca790be9',
    messagingSenderId: '829011178828',
    projectId: 'flutter-drivenui',
    storageBucket: 'flutter-drivenui.appspot.com',
    iosClientId:
        '829011178828-jkjbp60ib97ag8fqpu64n41ev0h9tlj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4eD4iL0VTRWHMVXRZelP_8JyBFxC8mHg',
    appId: '1:829011178828:ios:d5a9707775dcdaca790be9',
    messagingSenderId: '829011178828',
    projectId: 'flutter-drivenui',
    storageBucket: 'flutter-drivenui.appspot.com',
    iosClientId:
        '829011178828-jkjbp60ib97ag8fqpu64n41ev0h9tlj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
